branch-defaults:
  default:
    environment: Ebstest-env
environment-defaults:
  Ebstest-env:
    branch: null
    repository: null
global:
  application_name: ebstest
  default_ec2_keyname: null
  default_platform: Python 3.13 running on 64bit Amazon Linux 2023
  default_region: us-east-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  sc: null
  workspace_type: Application
